spring:
  application:
    name: panel-empresas-vascas

  datasource:
    url: ${DB_URL}
    username: ${DB_USUARIO}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Europe/Madrid

  jackson:
    time-zone: Europe/Madrid
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    eus.aaronduque.panelempresas: DEBUG
    org.hibernate.SQL: DEBUG